services:
  web-server:
    image: crccheck/hello-world
    container_name: hello-world-webserver
    ports:
      - 8000:8000
  tor-quick:
    image: ghcr.io/felix-zenk/tor-quick:latest
    container_name: tor-quick
    environment:
      FORWARD_ADDR1: 80:web-server:8000
      ## Uncomment if the forward destinations should be tested to be reachable
      # CHECK_DESTINATION: true
      ## Use vanguards
      # ENABLE_VANGUARDS: true
      ## Any extra options to write to the torrc file
      # TORRC_EXTRA: |
        # HardwareAccel 1
        # %include /volume/with/extra/*.conf

    ## You probably want to uncomment this when using CHECK_DESTINATION
    # depends_on:
      # - web-server

    ## If you want to use a set onion address, you can mount a volume with the private_key and hostname files
    # volumes:
      # - ./hidden_service:/var/lib/tor/hidden_service
      # - hidden-service:/var/lib/tor/hidden_service
    restart: unless-stopped

# volumes:
  # hidden-service:
